export { HomeView } from "./HomeView";
// export { BurnSPLView as BurnNFTView } from "./BurnNFTView";
export { SPLTokenView } from "./SPLTokenView";
// export { UploadView } from "./UploadView";
// export { SUATMMView } from "./SUATM²View";
// export { MultiSenderView } from "./MultiSenderView";
export { BurnSPLView } from "./BurnSPLView";
export { CloseAccountView } from "./CloseAccountView";
// export { UpdateNFTMetadataView } from "./UpdateNFTMetadataView";
// export { RevokeView } from "./RevokeView";
// export { CreateNFTCollectionView } from "./CreateNFTCollectionView";
